MySQL Connection Errors
Go into the credentials config of mysqlconnection.py and produce as many "mysql connection" errors as possible. Try using mistyped strings, incorrect usernames, unopened ports, and whatever other errors you can create.

(1)
sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)

fix - check the password in mysqlconnection.py

(2)
sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root1'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)

fix - check the usernames in mysqlconnection.py

(3)
sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)") (Background on this error at: http://sqlalche.me/e/e3q8)

fix - check the port number in mysqlconnection.py

(4)
sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.10' (60)") (Background on this error at: http://sqlalche.me/e/e3q8)

fix - check the localhost ip address in mysqlconnection.py

(5)
sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'friendsdb1'") (Background on this error at: http://sqlalche.me/e/e3q8)

fix - check the database name in the server.py

(6)
sqlalchemy.exc.ProgrammingError
ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'friendsdb.friend' doesn't exist") [SQL: u'SELECT * FROM friend'] (Background on this error at: http://sqlalche.me/e/f405)

fix - check the table name in the server.py

(7)
sqlalchemy.exc.StatementError
StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'first_names' [SQL: u'INSERT INTO friends (first_name, last_name, occupation, created_at, updated_at) VALUES (%s, %s, %s, NOW(), NOW())'] [parameters: [{'first_name': u'hello first', 'last_name': u'hello last', 'occupation': u'hello job'}]] (Background on this error at: http://sqlalche.me/e/cd3x)

fix - check the column name in the server.py (insert sql)

(8)
sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'first_names' in 'field list'") [SQL: u'UPDATE friends SET first_names = %s, last_name = %s, occupation = %s , updated_at = now() WHERE id = %s'] [parameters: (u'', u'', u'', u'99')] (Background on this error at: http://sqlalche.me/e/e3q8)

fix - check the column name in the server.py (update sql)

